### ISSUE TITLE
Could not parse plain Array without keys

### ISSUE THREAD

**Issue by vervatovskis** [matthewcheok/Realm-JSON#100]
How can I configure/parse JSON object like this 
[Screenshot](https://drive.google.com/file/d/0B73p5mPrvPYZTENzUUF5R0FFTXM/view?usp=sharing).

More explanation: It's an array of integers without keys like this:
`partitionIds: [6107,6108,6109,6110],`

**Comment by mpaulsonco** [comment]
I believe that this is a limitation with Realm as opposed to Realm-JSON. 

While [Realm supports storing arrays](https://realm.io/docs/objc/latest/#supported-types), they must be stored in an RLMArray, and RLMArrays [may only contain `RLMObject`s, not basic types such as a string or number](https://realm.io/docs/objc/latest/#nested-objects). This specific change has been tracked [on Realm Cocoa's issue tracker](https://github.com/realm/realm-cocoa/issues/1120).

I would suggest structuring your data so that you are storing an array of integers with keys. You might need to do some preprocessing on that JSON to change it into something like `[{"value": 6107}, {"value": 6108}, {"value": 6109}, {"value": 6110}]` and then create a RLMObject (with `Value: Int`) that is stored in a RLMArray on your parent object. While this is not ideal app-side, if you're in a situation where you have control over the JSON coming down, consider [changing it to confirm to jsonapi.org's latest specification](http://jsonapi.org/format/#document-top-level) which would help to avoid this issue.

Feel free to let me know if you need any further guidance, happy coding!

**Comment by vervatovskis** [comment]
Thanks Max for this clear and detailed answer. It really helps :)
